server:
  port: 9998
spring:
  application:
    name: zuul-gateway
  profiles:
    active: local
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
#这个用来开启 spring-boot-starter-actuator 模块 这个模块可以对 Spring Boot 构建的应用提供 一系列用于监控的端点。
management:
  endpoints:          #这里可以指定端口  不指定则默认为 server.port端口
    web:
      exposure:
        include: "*" #这个代表开启全部
#熔断器超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #路由转发的请求命令执行的超时时间
ribbon:
  ConnectTimeout: 10000 #路由转发的请求的时候，创建请求连接的超时时间。请求超时时当这个时间小于上面的熔断时间会进行重试路由请求
  ReadTimeout: 10000 #这个超时和上面的connectTimeOut类似 只是他是对创建请求连接之后的超时时间 这个值小于connectTimeout的值的时候会进行重试路由请求
  #可以设置重试次数具体参数看文档   zuul.retryable 全局关闭重试  zuul.routes.<route>.retryable=false指定路由服务关闭重试
restUrl:
  userServiceRest: http://USER-SERVICE-V1/